# Root railway.toml for monorepo
# This file is at the root to help Railway understand the structure
# Each service (backend/frontend) has its own railway.toml in its directory

[build]
builder = "NIXPACKS"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10